server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://niuroubuger-mysql.ns-30d7gjvu.svc:3306/Beef%20Pie?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qrzk4ts4
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.hello.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 文件上传配置
file:
  upload:
    path: /tmp/uploads/

# 对象存储配置
object:
  storage:
    access-key: tqd6953k
    secret-key: rlnqfq8c77tz9phq
    endpoint: https://objectstorageapi.hzh.sealos.run
    external-endpoint: https://objectstorageapi.hzh.sealos.run
    bucket: tqd6953k-yaxianzhi 